### ISSUE TITLE
OAuth2 Integration

### ISSUE THREAD

**Issue by blaketastic2** [choonchernlim/spring-security-adfs-saml2#15]
What is the best way to get this working with Spring oAuth2?

**Comment by choonchernlim** [comment]
You do not want to use this library to integrate with OAuth2 since it strictly relies on convoluted SAML protocol... it will be like doing multiple security protocol hops just to do what you do, and it will be impossible to get these protocols to play nicely.

If your app needs OAuth2 security, use `org.springframework.security.oauth:spring-security-oauth2:x.x.x` directly.
