### ISSUE TITLE
Multiple IDP Configuration

### ISSUE THREAD

**Issue by woody3000** [choonchernlim/spring-security-adfs-saml2#5]
I love how easy you've made setting up AD FS for me!  So I'd first like to say thanks!

It'd be great if this could handle multiple IDPs.  I _think_ all that would need be done is allow a dev to add multiple IDP server names and in metadata(), create multiple HTTPMetadataProviders with their own ExtendedMetadataDelegagte and add them all to the list passed to the CachingMetadataManager.

Thanks again!

**Comment by choonchernlim** [comment]
Glad you found it useful, @woody3000 .

My initial plan was to able to support multiple IDPs (for fallback, etc), but it quickly became very complicated because each IDP may require different SP configurations (due to different setups or ADFS versions). As a result, we may end up with one `SAMLConfigBean` per SP configuration, which led me to abandon that effort in attempt to simplify the already complicated configuration. 

That said, I believe you can override certain methods on your end to pull it off, assuming your IDPs share identical configurations.

Hope this helps.
